/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dashboard.components;

import com.dashboard.subcomponents.AddLectures;
import com.dashboard.subcomponents.ViewLectures;
import com.models.Lecturer;
import javax.swing.JTabbedPane;

/**
 *
 * @author ESHAN
 */
public class Lectures extends javax.swing.JPanel {

    /**
     * Creates new form Lectures
     */
    private JTabbedPane jTabbedPane;
    
    public Lectures(JTabbedPane jTabbedPane) {
        initComponents();
        this.jTabbedPane = jTabbedPane;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addLecturersBtn = new javax.swing.JButton();
        viewLecturersBtn = new javax.swing.JButton();

        addLecturersBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icons/Add-Folder-icon_1.png"))); // NOI18N
        addLecturersBtn.setText("ADD LECTURERS");
        addLecturersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLecturersBtnActionPerformed(evt);
            }
        });

        viewLecturersBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icons/Actions-view-calendar-list-icon.png"))); // NOI18N
        viewLecturersBtn.setText("VIEW LECTURERS");
        viewLecturersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewLecturersBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addComponent(addLecturersBtn)
                .addGap(26, 26, 26)
                .addComponent(viewLecturersBtn)
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(182, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewLecturersBtn)
                    .addComponent(addLecturersBtn))
                .addContainerGap(173, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addLecturersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLecturersBtnActionPerformed
        // TODO add your handling code here:
        jTabbedPane.remove(0);
        jTabbedPane.add("Add Lecturers", new AddLectures(new Lecturer(), jTabbedPane));
    }//GEN-LAST:event_addLecturersBtnActionPerformed

    private void viewLecturersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewLecturersBtnActionPerformed
        // TODO add your handling code here:
        jTabbedPane.remove(0);
        jTabbedPane.add("View Lecturers", new ViewLectures(jTabbedPane));
    }//GEN-LAST:event_viewLecturersBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addLecturersBtn;
    private javax.swing.JButton viewLecturersBtn;
    // End of variables declaration//GEN-END:variables
}
