/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dashboard.components;

import com.dashboard.subcomponents.AddEditBuilding;
import com.dashboard.subcomponents.AddEditRoom;
import com.dashboard.subcomponents.AddNotAvailableTimesforRoom;
import com.dashboard.subcomponents.RoomManagement;
import com.dashboard.subcomponents.ViewBuilding;
import com.dashboard.subcomponents.ViewRoom;
import com.models.Building;
import com.models.Room;
import com.services.LecturerService;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author ESHAN
 */
public class Location extends javax.swing.JPanel {

    /**
     * Creates new form Location
     */
    private JTabbedPane jTabbedPane;
    
    public Location(JTabbedPane jTabbedPane) {
        initComponents();
        this.jTabbedPane = jTabbedPane;
        
//        LecturerService service = new LecturerService();
//        building_jTable.setModel(DbUtils.resultSetToTableModel(service.tableLoadbuilding()));
//        room_jTable.setModel(DbUtils.resultSetToTableModel(service.tableLoadRooms()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addSubjectsBtn = new javax.swing.JButton();
        viewSubjectsBtn = new javax.swing.JButton();
        addBulidingBtn = new javax.swing.JButton();
        addRoomBtn = new javax.swing.JButton();
        roomManagementBtn = new javax.swing.JButton();
        roomManagementBtn1 = new javax.swing.JButton();
        roomManagementBtn2 = new javax.swing.JButton();

        addSubjectsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icons/Actions-view-calendar-list-icon.png"))); // NOI18N
        addSubjectsBtn.setText("VIEW BUILDINGS");
        addSubjectsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSubjectsBtnActionPerformed(evt);
            }
        });

        viewSubjectsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icons/Actions-view-calendar-list-icon.png"))); // NOI18N
        viewSubjectsBtn.setText("VIEW ROOMS");
        viewSubjectsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSubjectsBtnActionPerformed(evt);
            }
        });

        addBulidingBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icons/Add-Folder-icon_1.png"))); // NOI18N
        addBulidingBtn.setText("ADD BUILDING");
        addBulidingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBulidingBtnActionPerformed(evt);
            }
        });

        addRoomBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icons/Add-Folder-icon_1.png"))); // NOI18N
        addRoomBtn.setText("ADD ROOM");
        addRoomBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRoomBtnActionPerformed(evt);
            }
        });

        roomManagementBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icons/Add-Folder-icon_1.png"))); // NOI18N
        roomManagementBtn.setText("ADD CONSESTIVE SESSIONS ROOMS");
        roomManagementBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomManagementBtnActionPerformed(evt);
            }
        });

        roomManagementBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icons/Actions-view-calendar-list-icon.png"))); // NOI18N
        roomManagementBtn1.setText("ROOM MANAGEMENT");
        roomManagementBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomManagementBtn1ActionPerformed(evt);
            }
        });

        roomManagementBtn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icons/Add-Folder-icon_1.png"))); // NOI18N
        roomManagementBtn2.setText("ADD TIME NOT RESERVED");
        roomManagementBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomManagementBtn2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(addBulidingBtn)
                .addGap(18, 18, 18)
                .addComponent(addRoomBtn)
                .addGap(18, 18, 18)
                .addComponent(addSubjectsBtn)
                .addGap(18, 18, 18)
                .addComponent(viewSubjectsBtn)
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(roomManagementBtn1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(roomManagementBtn2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(roomManagementBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(150, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewSubjectsBtn)
                    .addComponent(addSubjectsBtn)
                    .addComponent(addBulidingBtn)
                    .addComponent(addRoomBtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roomManagementBtn)
                    .addComponent(roomManagementBtn2)
                    .addComponent(roomManagementBtn1))
                .addContainerGap(83, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addSubjectsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSubjectsBtnActionPerformed
        // TODO add your handling code here:
        jTabbedPane.remove(0);
        jTabbedPane.add("View buildings", new ViewBuilding(jTabbedPane));
    }//GEN-LAST:event_addSubjectsBtnActionPerformed

    private void viewSubjectsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSubjectsBtnActionPerformed
        // TODO add your handling code here:
        jTabbedPane.remove(0);
        jTabbedPane.add("View Rooms", new ViewRoom(jTabbedPane));
    }//GEN-LAST:event_viewSubjectsBtnActionPerformed

    private void addBulidingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBulidingBtnActionPerformed
        // TODO add your handling code here:
        jTabbedPane.remove(0);
        jTabbedPane.add("Add New Building", new AddEditBuilding(new Building(), jTabbedPane));
    }//GEN-LAST:event_addBulidingBtnActionPerformed

    private void addRoomBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRoomBtnActionPerformed
        // TODO add your handling code here:
        jTabbedPane.remove(0);
        jTabbedPane.add("Add New Room", new AddEditRoom(new Room(), jTabbedPane));
    }//GEN-LAST:event_addRoomBtnActionPerformed

    private void roomManagementBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomManagementBtnActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_roomManagementBtnActionPerformed

    private void roomManagementBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomManagementBtn1ActionPerformed
        // TODO add your handling code here:
        jTabbedPane.remove(0);
        jTabbedPane.add("Room Management", new RoomManagement());
    }//GEN-LAST:event_roomManagementBtn1ActionPerformed

    private void roomManagementBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomManagementBtn2ActionPerformed
        // TODO add your handling code here:
        jTabbedPane.remove(0);
        jTabbedPane.add("Add time room not reserved", new AddNotAvailableTimesforRoom());
    }//GEN-LAST:event_roomManagementBtn2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBulidingBtn;
    private javax.swing.JButton addRoomBtn;
    private javax.swing.JButton addSubjectsBtn;
    private javax.swing.JButton roomManagementBtn;
    private javax.swing.JButton roomManagementBtn1;
    private javax.swing.JButton roomManagementBtn2;
    private javax.swing.JButton viewSubjectsBtn;
    // End of variables declaration//GEN-END:variables
}
