/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dashboard.components;

import com.services.LecturerService;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author ESHAN
 */
public class Location extends javax.swing.JPanel {

    /**
     * Creates new form Location
     */
    public Location() {
        initComponents();
        
//        LecturerService service = new LecturerService();
//        building_jTable.setModel(DbUtils.resultSetToTableModel(service.tableLoadbuilding()));
//        room_jTable.setModel(DbUtils.resultSetToTableModel(service.tableLoadRooms()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addSubjectsBtn = new javax.swing.JButton();
        viewSubjectsBtn = new javax.swing.JButton();
        addSubjectsBtn1 = new javax.swing.JButton();
        viewSubjectsBtn1 = new javax.swing.JButton();

        addSubjectsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icons/Add-Folder-icon_1.png"))); // NOI18N
        addSubjectsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSubjectsBtnActionPerformed(evt);
            }
        });

        viewSubjectsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icons/Actions-view-calendar-list-icon.png"))); // NOI18N
        viewSubjectsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSubjectsBtnActionPerformed(evt);
            }
        });

        addSubjectsBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icons/Add-Folder-icon_1.png"))); // NOI18N
        addSubjectsBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSubjectsBtn1ActionPerformed(evt);
            }
        });

        viewSubjectsBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icons/Actions-view-calendar-list-icon.png"))); // NOI18N
        viewSubjectsBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSubjectsBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addComponent(addSubjectsBtn1)
                .addGap(18, 18, 18)
                .addComponent(viewSubjectsBtn1)
                .addGap(18, 18, 18)
                .addComponent(addSubjectsBtn)
                .addGap(18, 18, 18)
                .addComponent(viewSubjectsBtn)
                .addContainerGap(106, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(177, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewSubjectsBtn)
                    .addComponent(addSubjectsBtn)
                    .addComponent(addSubjectsBtn1)
                    .addComponent(viewSubjectsBtn1))
                .addContainerGap(168, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addSubjectsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSubjectsBtnActionPerformed
        // TODO add your handling code here:
//        jTabbedPane.remove(0);
//        jTabbedPane.add("Add Subjects", new AddEditSubjects(new Subject(), jTabbedPane));
    }//GEN-LAST:event_addSubjectsBtnActionPerformed

    private void viewSubjectsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSubjectsBtnActionPerformed
        // TODO add your handling code here:
//        jTabbedPane.remove(0);
//        jTabbedPane.add("View Subjects", new ViewSubjects(jTabbedPane));
    }//GEN-LAST:event_viewSubjectsBtnActionPerformed

    private void addSubjectsBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSubjectsBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addSubjectsBtn1ActionPerformed

    private void viewSubjectsBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSubjectsBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewSubjectsBtn1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSubjectsBtn;
    private javax.swing.JButton addSubjectsBtn1;
    private javax.swing.JButton viewSubjectsBtn;
    private javax.swing.JButton viewSubjectsBtn1;
    // End of variables declaration//GEN-END:variables
}
