/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dashboard.components;

import com.dashboard.subcomponents.AddEditSessions;
import com.dashboard.subcomponents.ViewSessions;
import com.models.Session;
import javax.swing.JTabbedPane;

/**
 *
 * @author ESHAN
 */
public class Sessions extends javax.swing.JPanel {

    /**
     * Creates new form Sessions
     */
    private JTabbedPane jTabbedPane;
    
    public Sessions(JTabbedPane jTabbedPane) {
        initComponents();
        this.jTabbedPane = jTabbedPane;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addSessionsBtn = new javax.swing.JButton();
        viewSessionsBtn = new javax.swing.JButton();

        addSessionsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icons/Add-Folder-icon_1.png"))); // NOI18N
        addSessionsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSessionsBtnActionPerformed(evt);
            }
        });

        viewSessionsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icons/Actions-view-calendar-list-icon.png"))); // NOI18N
        viewSessionsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSessionsBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(264, Short.MAX_VALUE)
                .addComponent(addSessionsBtn)
                .addGap(26, 26, 26)
                .addComponent(viewSessionsBtn)
                .addContainerGap(266, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(200, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewSessionsBtn)
                    .addComponent(addSessionsBtn))
                .addContainerGap(191, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addSessionsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSessionsBtnActionPerformed
        // TODO add your handling code here:
        jTabbedPane.remove(0);
        jTabbedPane.add("Add Sessions", new AddEditSessions(new Session(), jTabbedPane));
    }//GEN-LAST:event_addSessionsBtnActionPerformed

    private void viewSessionsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSessionsBtnActionPerformed
        // TODO add your handling code here:
        jTabbedPane.remove(0);
        jTabbedPane.add("View Subjects", new ViewSessions(jTabbedPane));
    }//GEN-LAST:event_viewSessionsBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSessionsBtn;
    private javax.swing.JButton viewSessionsBtn;
    // End of variables declaration//GEN-END:variables
}
