/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dashboard.subcomponents;

import com.services.RoomService;
import com.services.SessionService;
import com.services.TagServices;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ESHAN
 */
public class RoomManagement extends javax.swing.JPanel {

    /**
     * Creates new form RoomManagement
     */
    
    
    public RoomManagement() {
        initComponents();
        
        
        SessionService service = new SessionService();
        ResultSet sessionResult = service.tableLoadSessions();
        
        try {
            session_jCombobox.addItem("-select-");
            while (sessionResult.next()) {
                String sessiontxt = 
                         sessionResult.getString(2)+"   -   "
                        +sessionResult.getString(3)+"   -   "
                        +sessionResult.getString(4)+"   -   "
                        +sessionResult.getString(5)+"   -   "
                        +sessionResult.getString(6);
                session_jCombobox.addItem(sessiontxt);
            }
        } catch (SQLException ex) {
            Logger.getLogger(RoomManagement.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        duration_jTextfeild = new javax.swing.JTextField();
        tag_jCombobox = new javax.swing.JComboBox<>();
        session_jCombobox = new javax.swing.JComboBox<>();
        tag_jTextFeild = new javax.swing.JTextField();
        clear_tag_text_btn = new javax.swing.JButton();
        subject_jCombobox = new javax.swing.JComboBox<>();
        subject_jTextFeild = new javax.swing.JTextField();
        clear_subject_text_btn = new javax.swing.JButton();
        lecturer_jCombobox = new javax.swing.JComboBox<>();
        lecturer_jTextFeild = new javax.swing.JTextField();
        clear_lecturer_text_btn = new javax.swing.JButton();
        student_jCombobox = new javax.swing.JComboBox<>();
        student_jTextFeild = new javax.swing.JTextField();
        clear_student_text_btn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        addSessionsBtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Lecturer Preffered");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Subject Preffered");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Tag Preffered");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Session");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("D");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Student Preffered");

        duration_jTextfeild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duration_jTextfeildActionPerformed(evt);
            }
        });
        duration_jTextfeild.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                duration_jTextfeildKeyReleased(evt);
            }
        });

        tag_jCombobox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tag_jComboboxItemStateChanged(evt);
            }
        });
        tag_jCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tag_jComboboxActionPerformed(evt);
            }
        });

        session_jCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                session_jComboboxActionPerformed(evt);
            }
        });

        tag_jTextFeild.setEditable(false);

        clear_tag_text_btn.setText("X");
        clear_tag_text_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_tag_text_btnActionPerformed(evt);
            }
        });

        subject_jCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subject_jComboboxActionPerformed(evt);
            }
        });

        subject_jTextFeild.setEditable(false);

        clear_subject_text_btn.setText("X");
        clear_subject_text_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_subject_text_btnActionPerformed(evt);
            }
        });

        lecturer_jCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lecturer_jComboboxActionPerformed(evt);
            }
        });

        lecturer_jTextFeild.setEditable(false);

        clear_lecturer_text_btn.setText("X");
        clear_lecturer_text_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_lecturer_text_btnActionPerformed(evt);
            }
        });

        student_jCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                student_jComboboxActionPerformed(evt);
            }
        });

        student_jTextFeild.setEditable(false);

        clear_student_text_btn.setText("X");
        clear_student_text_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_student_text_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(133, 133, 133)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(tag_jCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tag_jTextFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clear_tag_text_btn))
                            .addComponent(session_jCombobox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(100, 100, 100)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(duration_jTextfeild)
                                .addGap(42, 42, 42))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(subject_jCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(subject_jTextFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(clear_subject_text_btn))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(student_jCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(student_jTextFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(clear_student_text_btn))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(lecturer_jCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lecturer_jTextFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(clear_lecturer_text_btn)))
                                .addContainerGap())))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(session_jCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tag_jTextFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clear_tag_text_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tag_jCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(subject_jTextFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clear_subject_text_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subject_jCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lecturer_jTextFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clear_lecturer_text_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lecturer_jCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(student_jTextFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clear_student_text_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(student_jCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(duration_jTextfeild, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(jLabel7))
                .addGap(111, 111, 111))
        );

        addSessionsBtn.setText("Add Sessions");
        addSessionsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSessionsBtnActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addSessionsBtn)
                .addGap(49, 49, 49)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(addSessionsBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tag_jComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tag_jComboboxActionPerformed
        // TODO add your handling code here:
        if (tag_jCombobox.getSelectedIndex() == 0) {
            System.out.println("---------------");
        }else{

            try {
                String tagrname = tag_jCombobox.getSelectedItem().toString();

            if (tag_jTextFeild.getText().contains(tagrname)) {
                JOptionPane.showMessageDialog(null, "Room already added");
            }else{
                if (tag_jTextFeild.getText().equals("")) {
                    tag_jTextFeild.setText(tagrname);
                }else{
                    tag_jTextFeild.setText(tag_jTextFeild.getText()+", "+tagrname);
                }
            }
            } catch (Exception e) {
            }
            
            //lecturer_jCombobox.setSelectedIndex(0);

        }
    }//GEN-LAST:event_tag_jComboboxActionPerformed

    private void clear_tag_text_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_tag_text_btnActionPerformed
        // TODO add your handling code here:
        tag_jTextFeild.setText("");
    }//GEN-LAST:event_clear_tag_text_btnActionPerformed

    private void addSessionsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSessionsBtnActionPerformed
        // TODO add your handling code here:

//        if (lecturers_jTextFeild.getText().toString().equals("") || subject_jCombobox.getSelectedIndex() == 0
//            || tag_jCombobox.getSelectedIndex() == 0 || groupId_jCombobox.getSelectedIndex() == 0
//            || studentCount_textfeild.getText().toString().equals("")
//            || duration_jTextfeild.getText().toString().equals("")) {
//
//            showAlertDialog("error", "Please fill all feilds");
//        }else{
//            Session session = new Session();
//            session.setSessionId(sessionid);
//            session.setLecturers(lecturers_jTextFeild.getText().toString());
//            session.setSubject(subject_jCombobox.getSelectedItem().toString());
//            session.setTag(tag_jCombobox.getSelectedItem().toString());
//            session.setGroup(groupId_jCombobox.getSelectedItem().toString());
//            session.setNumberOfStudents(Integer.parseInt(studentCount_textfeild.getText()));
//            session.setDuration(Integer.parseInt(duration_jTextfeild.getText()));
//
//            SessionService service = new SessionService();
//
//            if (addSessionsBtn.getText().toLowerCase().contains("add")) {
//                if (service.addSession(session)) {
//                    showAlertDialog("success", "Session successfully added! Do you want to view all sessions");
//                    clearfeilds();
//                }else{
//                    showAlertDialog("error", "Session added failed! please try again");
//                }
//            }else{
//                if (sessionid == 0) {
//                    showAlertDialog("error", "Session update error! please try again");
//                }else{
//                    if (service.updateSession(session)) {
//                        showAlertDialog("success", "Session successfully updated! Do you want to view all sessions");
//                        clearfeilds();
//                    }else{
//                        showAlertDialog("error", "Session update failed! please try again");
//                    }
//
//                }
//            }
//        }

    }//GEN-LAST:event_addSessionsBtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //        jTabbedPane.remove(0);
        //        jTabbedPane.add("Subjects", new Subjects(jTabbedPane));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void subject_jComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subject_jComboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subject_jComboboxActionPerformed

    private void clear_subject_text_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_subject_text_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clear_subject_text_btnActionPerformed

    private void lecturer_jComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lecturer_jComboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lecturer_jComboboxActionPerformed

    private void clear_lecturer_text_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_lecturer_text_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clear_lecturer_text_btnActionPerformed

    private void student_jComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_student_jComboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_student_jComboboxActionPerformed

    private void clear_student_text_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_student_text_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clear_student_text_btnActionPerformed

    private void session_jComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_session_jComboboxActionPerformed
        // TODO add your handling code here:
        if (session_jCombobox.getSelectedIndex() == 0) {
            System.out.println("--------------");
            tag_jCombobox.setEnabled(false);
            subject_jCombobox.setEnabled(false);
            lecturer_jCombobox.setEnabled(false);
            student_jCombobox.setEnabled(false);
        }else{
            tag_jCombobox.setEnabled(true);
            subject_jCombobox.setEnabled(true);
            lecturer_jCombobox.setEnabled(true);
            student_jCombobox.setEnabled(true);
            
            tag_jCombobox.removeAllItems();
            subject_jCombobox.removeAllItems();
            lecturer_jCombobox.removeAllItems();
            student_jCombobox.removeAllItems();
            
            
            
            String[] sessiontxt = session_jCombobox.getSelectedItem().toString().split("-");
//            String lecturer = sessiontxt[0];
           
            System.out.println(sessiontxt[0].trim());
            System.out.println(sessiontxt[1].trim());
            System.out.println(sessiontxt[2].trim());
            System.out.println(sessiontxt[3].trim());
            System.out.println(sessiontxt[4].trim());
//            System.out.println(sessiontxt[3]);
//            System.out.println(sessiontxt[4]);
//            System.out.println(sessiontxt[5]);
            
            RoomService roomService = new RoomService();
            ResultSet roomResult = roomService.tableLoadRooms();
                        
            try {
                if (sessiontxt[2].trim().toLowerCase().contains("tutorial") || sessiontxt[2].trim().toLowerCase().contains("lecture")) {
                    while (roomResult.next()) {
                        if (roomResult.getString("type").toLowerCase().contains("hall")) {
                            tag_jCombobox.addItem(roomResult.getString(3));
                            subject_jCombobox.addItem(roomResult.getString(3));
                            lecturer_jCombobox.addItem(roomResult.getString(3));
                            student_jCombobox.addItem(roomResult.getString(3));
                        }
                    }
                }else if (sessiontxt[2].trim().toLowerCase().contains("lab")) {
                    while (roomResult.next()) {
                        if (roomResult.getString("type").toLowerCase().contains("lab")) {
                            tag_jCombobox.addItem(roomResult.getString(3));
                            subject_jCombobox.addItem(roomResult.getString(3));
                            lecturer_jCombobox.addItem(roomResult.getString(3));
                            student_jCombobox.addItem(roomResult.getString(3));
                            if (sessiontxt[1].trim().toLowerCase().contains("ios") && roomResult.getString(3).toLowerCase().contains("im")) {
                                subject_jCombobox.removeAllItems();
                                lecturer_jCombobox.removeAllItems();
                                student_jCombobox.removeAllItems();
                                subject_jCombobox.addItem(roomResult.getString(3));
                                lecturer_jCombobox.addItem(roomResult.getString(3));
                                student_jCombobox.addItem(roomResult.getString(3));
                            }
                        }
                    }
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(RoomManagement.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_session_jComboboxActionPerformed

    private void duration_jTextfeildKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_duration_jTextfeildKeyReleased
        // TODO add your handling code here:
        //        try {
            //            int x = Integer.parseInt(duration_jTextfeild.getText());
            //        } catch (NumberFormatException nfe) {
            //            JOptionPane.showMessageDialog(null, "Invalid duration");
            //            duration_jTextfeild.setText("");
            //        }
    }//GEN-LAST:event_duration_jTextfeildKeyReleased

    private void duration_jTextfeildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duration_jTextfeildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_duration_jTextfeildActionPerformed

    private void tag_jComboboxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tag_jComboboxItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_tag_jComboboxItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSessionsBtn;
    private javax.swing.JButton clear_lecturer_text_btn;
    private javax.swing.JButton clear_student_text_btn;
    private javax.swing.JButton clear_subject_text_btn;
    private javax.swing.JButton clear_tag_text_btn;
    private javax.swing.JTextField duration_jTextfeild;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JComboBox<String> lecturer_jCombobox;
    private javax.swing.JTextField lecturer_jTextFeild;
    private javax.swing.JComboBox<String> session_jCombobox;
    private javax.swing.JComboBox<String> student_jCombobox;
    private javax.swing.JTextField student_jTextFeild;
    private javax.swing.JComboBox<String> subject_jCombobox;
    private javax.swing.JTextField subject_jTextFeild;
    private javax.swing.JComboBox<String> tag_jCombobox;
    private javax.swing.JTextField tag_jTextFeild;
    // End of variables declaration//GEN-END:variables
}
