/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dashboard.subcomponents;

import com.models.Session;
import com.services.SessionService;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author ESHAN
 */
public class ViewSessions extends javax.swing.JPanel {

    /**
     * Creates new form ViewSessions
     */
    private JTabbedPane jTabbedPane;
    private Vector originalTableModel;
    
    public ViewSessions(JTabbedPane jTabbedPane) {
        initComponents();
        this.jTabbedPane = jTabbedPane;
        SessionService service = new SessionService();
        sessions_jTable.setModel(DbUtils.resultSetToTableModel(service.tableLoadSessions()));
        originalTableModel = (Vector) ((DefaultTableModel) sessions_jTable.getModel()).getDataVector().clone();
//        sessions_jTable.getColumnModel().getColumn(0).setHeaderValue("ID");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        sessions_jTable = new javax.swing.JTable();
        deleteSessionsBtn = new javax.swing.JButton();
        editSessionsBtn = new javax.swing.JButton();
        search_jTextField = new javax.swing.JTextField();

        sessions_jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(sessions_jTable);

        deleteSessionsBtn.setText("Delete");
        deleteSessionsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteSessionsBtnActionPerformed(evt);
            }
        });

        editSessionsBtn.setText("Edit");
        editSessionsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editSessionsBtnActionPerformed(evt);
            }
        });

        search_jTextField.setToolTipText("Search All");
        search_jTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                search_jTextFieldKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(search_jTextField)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(deleteSessionsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editSessionsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(156, Short.MAX_VALUE)
                .addComponent(editSessionsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deleteSessionsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(172, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(search_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deleteSessionsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteSessionsBtnActionPerformed
        // TODO add your handling code here:
        int row = sessions_jTable.getSelectedRow();

        if (row >= 0) {
            int sessionid = Integer.parseInt(sessions_jTable.getValueAt(row, 0).toString());

            int i = JOptionPane.showConfirmDialog(this, "Delete selected session" ,"Confirm", JOptionPane.YES_NO_OPTION);
            if(i==0){
                SessionService service = new SessionService();
                if (service.deleteSession(sessionid)) {
                    JOptionPane.showMessageDialog(this, "Session delete successful");
                }else{
                    JOptionPane.showMessageDialog(this, "Building delete failed");
                }
                
            }
            //refresh table
            jTabbedPane.remove(0);
            jTabbedPane.add("View Sessions", new ViewSessions(jTabbedPane));
        }else{
            JOptionPane.showMessageDialog(this, "Please select row!");
        }
    }//GEN-LAST:event_deleteSessionsBtnActionPerformed

    private void editSessionsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editSessionsBtnActionPerformed
        // TODO add your handling code here:
        int row = sessions_jTable.getSelectedRow();

        if (row >= 0) {
            int sessionid = (int) sessions_jTable.getValueAt(row, 0);
            String lecturer = sessions_jTable.getValueAt(row, 1).toString();
            String subject = sessions_jTable.getValueAt(row, 2).toString();
            String tag = sessions_jTable.getValueAt(row, 3).toString();
            String groupid = sessions_jTable.getValueAt(row, 4).toString();
            int stuCount = (int) sessions_jTable.getValueAt(row, 5);
            int duration = (int) sessions_jTable.getValueAt(row, 6);

            Session session = new Session(lecturer, tag, groupid, subject, stuCount, duration);
            session.setSessionId(sessionid);
            
            jTabbedPane.remove(0);
            jTabbedPane.add("Edit Building Details", new AddEditSessions(session, jTabbedPane));
        }else{
            JOptionPane.showMessageDialog(this, "Please select row!");
        }

    }//GEN-LAST:event_editSessionsBtnActionPerformed

    private void search_jTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_jTextFieldKeyReleased
        // TODO add your handling code here:
        searchTableContents(search_jTextField.getText().toString());
    }//GEN-LAST:event_search_jTextFieldKeyReleased

    public void searchTableContents(String searchString) {    
    DefaultTableModel currtableModel = (DefaultTableModel) sessions_jTable.getModel();
      currtableModel.setRowCount(0);
      for (Object rows : originalTableModel) {
          Vector rowVector = (Vector) rows;
          for (Object column : rowVector) {
              if (column.toString().toLowerCase().contains(searchString.toLowerCase())) {
                  currtableModel.addRow(rowVector);
                  break;
              }
          }

      }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteSessionsBtn;
    private javax.swing.JButton editSessionsBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField search_jTextField;
    private javax.swing.JTable sessions_jTable;
    // End of variables declaration//GEN-END:variables
}
