/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dashboard.subcomponents;

import com.dashboard.components.*;
import com.models.Lecturer;
import com.models.Subject;
import com.services.LecturerService;
import com.services.SubjectService;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author ESHAN
 */
public class ViewSubjects extends javax.swing.JPanel {

    /**
     * Creates new form Lectures
     */
    private JTabbedPane jTabbedPane;
    
    public ViewSubjects(JTabbedPane jTabbedPane) {
        initComponents();
        this.jTabbedPane = jTabbedPane;
        SubjectService service = new SubjectService();
        viewSubjectsTable.setModel(DbUtils.resultSetToTableModel(service.tableLoadSubjects()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        viewSubjectsTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        deleteBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        subnameLable = new javax.swing.JLabel();

        viewSubjectsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        viewSubjectsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewSubjectsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(viewSubjectsTable);

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        editBtn.setText("Edit");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        subnameLable.setText("jLabel1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(subnameLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(subnameLable)
                .addGap(65, 65, 65)
                .addComponent(editBtn)
                .addGap(18, 18, 18)
                .addComponent(deleteBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 774, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewSubjectsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewSubjectsTableMouseClicked
        // TODO add your handling code here:
        int row = viewSubjectsTable.getSelectedRow();
        int subid = (int) viewSubjectsTable.getValueAt(row, 0);
        String subname = viewSubjectsTable.getValueAt(row, 1).toString();
        String scode = viewSubjectsTable.getValueAt(row, 2).toString();
        String oy = viewSubjectsTable.getValueAt(row, 3).toString();
        String os = viewSubjectsTable.getValueAt(row, 4).toString();
        int lecHours = (int) viewSubjectsTable.getValueAt(row, 5);
        int tuteHours = (int) viewSubjectsTable.getValueAt(row, 6);
        int labHours = (int) viewSubjectsTable.getValueAt(row, 7);
        int evalHours = (int) viewSubjectsTable.getValueAt(row, 8);
        subnameLable.setText(subname);
        
    }//GEN-LAST:event_viewSubjectsTableMouseClicked

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        // TODO add your handling code here:
        int row = viewSubjectsTable.getSelectedRow();
        
        if (row >= 0) {
            int subid = (int) viewSubjectsTable.getValueAt(row, 0);
            String subname = viewSubjectsTable.getValueAt(row, 1).toString();
            String scode = viewSubjectsTable.getValueAt(row, 2).toString();
            String oy = viewSubjectsTable.getValueAt(row, 3).toString();
            String os = viewSubjectsTable.getValueAt(row, 4).toString();
            int lecHours = (int) viewSubjectsTable.getValueAt(row, 5);
            int tuteHours = (int) viewSubjectsTable.getValueAt(row, 6);
            int labHours = (int) viewSubjectsTable.getValueAt(row, 7);
            int evalHours = (int) viewSubjectsTable.getValueAt(row, 8);

            Subject s = new Subject(subname, scode, oy, os, lecHours, tuteHours, labHours, evalHours);
            s.setSubjectId(subid);

            jTabbedPane.remove(0);
            jTabbedPane.add("Edit Subject Details", new AddEditSubjects(s, jTabbedPane));
        }else{
            JOptionPane.showMessageDialog(this, "Please select row!");
        }
        
        
    }//GEN-LAST:event_editBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed

        int row = viewSubjectsTable.getSelectedRow();
        
        if (row >= 0) {
            int subid = Integer.parseInt(viewSubjectsTable.getValueAt(row, 0).toString());
            String subname = viewSubjectsTable.getValueAt(row, 1).toString().toUpperCase();

            int i = JOptionPane.showConfirmDialog(this, "Delete "+subname ,"Confirm", JOptionPane.YES_NO_OPTION);
            if(i==0){
                SubjectService service = new SubjectService();
                service.deleteSubject(subid);
                JOptionPane.showMessageDialog(this, "Lecturer delete successful");
            }
        //refresh table
            jTabbedPane.remove(0);
            jTabbedPane.add("View Subjects", new ViewSubjects(jTabbedPane));
        }else{
            JOptionPane.showMessageDialog(this, "Please select row!");
        }
        
        
    }//GEN-LAST:event_deleteBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel subnameLable;
    private javax.swing.JTable viewSubjectsTable;
    // End of variables declaration//GEN-END:variables
}
